// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etrxbijkvrbatuayqjgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cnhiaWprdnJiYXR1YXlxamdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMDk5NzUsImV4cCI6MjA4Nzg4NTk3NX0._3ExM3EWI4ssc3nEaU_u7s2RyPHV8D5Q5-xr0VSBpZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    detectSessionInUrl: true,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'parapaquetes-auth',
    lock: async <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
      // Bypass navigator.locks which doesn't work in cross-origin iframes
      return await fn();
    },
  },
  global: {
    headers: { 'X-Client-Info': 'parapaquetes-print-studio' },
  },
});